Finished mobile version
sonyco-4u/Portfolio-microverse2 pull request #2
Opened 2022-08-20 17:10 UTC by sonyco-4u

- Used Flexbox to place elements in the page.
- Used CSS Grid to place elements in the page.
- Built a personal portfolio site.

2022-08-20 18:03 UTC, mgmediaweb requested changes
Hi @sonyco-4u, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost2](https://user-images.githubusercontent.com/41912912/185759481-1bc23937-06a5-44fd-982e-eaeebb61aabe.gif)

## Highlights 💯 

- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️
- Very good structure of your site.  ✔️
- Very well applied design.  ✔️


## Required Changes ♻️

Kindly, I recommend you modify the README file with the corresponding Title and Description of your project, this will help a possible recruiter to easily know what your project consists of in the future.

Kindly, you should put a little margin between the logo and the text, it would look better your work and it would be more similar to the original design of Figma
![image](https://user-images.githubusercontent.com/41912912/185759532-34c146d7-bb15-4e0a-8ab5-7bf370a2dd46.png)

Kindly, I recommend you to improve the padding a little so that it looks better and more closely resembles the original design of Figma
![image](https://user-images.githubusercontent.com/41912912/185759914-dcd1fd24-595e-4e7b-a64e-2c13724747a1.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 18:03 UTC, mgmediaweb commented on style.css
> +}
Kindly, I recommend you use more descriptive class names so that in the future you or another partner understands your code better.

2022-08-20 18:03 UTC, mgmediaweb commented on style.css
> +  width: 327px;
Kindly, I recommend that you do not limit the texts with a fixed width, but that they adapt freely to the container

2022-08-20 18:03 UTC, mgmediaweb commented on style.css
> +  width: 124px;
Kindly, I recommend you manage the dimensions of the buttons with padding instead of fixed measurements with width

2022-08-20 21:48 UTC, sonyco-4u commented on index.html
> +      <main>
I tried changing it but is affecting all work

2022-08-20 21:49 UTC, sonyco-4u commented on index.html
> +            <h4>Tonic</h4>
I Used H4 for my second Tittle

2022-08-20 21:56 UTC, mgmediaweb commented on index.html
> +            <h4>Tonic</h4>
yes I saw it, the normal thing would be that it was H3 (because you use H1, H2, and then H4)

2022-08-20 22:05 UTC, sonyco-4u commented on index.html
> +            <h4>Tonic</h4>
okay, I have just corrected that

2022-08-20 22:06 UTC, sonyco-4u commented on style.css
> +  margin-top: 114px;
How can I achieve this?

2022-08-20 22:08 UTC, mgmediaweb commented on style.css
> +  margin-top: 114px;
use display:flex, align-items, justify-contents

2022-08-21 00:57 UTC, sonyco-4u commented
All error fixed

On Sat, 20 Aug 2022 at 15:08, Gonzalo Medina ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In style.css
> <https://github.com/sonyco-4u/Portfolio-microverse2/pull/2#discussion_r950748134>
> :
>
> > +  background-image: url("../img/Snapshoot-Portfolio3.png");
> +  margin-top: 88px;
> +}
> +
> +.show-case4 {
> +  background-image: url("../img/Snapshoot-Portfolio4.png");
> +  margin-top: 88px;
> +}
> +
> +#about-me {
> +  flex-direction: column;
> +  width: 375px;
> +  background: #fff;
> +  display: flex;
> +  border-top-right-radius: 80px;
> +  margin-top: 114px;
>
> use display:flex, align-items, justify-contents
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sonyco-4u/Portfolio-microverse2/pull/2#discussion_r950748134>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO2KAPMI4EW6JHVRZUREZZLV2FJMZANCNFSM57DQIX5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-21 03:38 UTC, emmiiorji approved these changes
Hi @sonyco-4u, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![brilliant-well-done](https://user-images.githubusercontent.com/20554583/185774339-06cdbb67-a06b-4459-84b4-a77ecea00e78.gif)


## Highlights

- Linter checks are passing
- Good commit messages
- Beautiful design


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-29 17:51 UTC, merged